import {StyleSheet} from 'react-native';

import {Colors} from '../GlobalStyle';

export default styles = StyleSheet.create({
  viewItemProductAvailable: {
    pointerEvents: 'auto',
    opacity: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    padding: 10,
    paddingTop: 5,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    marginHorizontal: 10,
    marginTop: 2,
    marginBottom: 8,
  },
  viewItemProductDeleted: {
    pointerEvents: 'none',
    opacity: 0.6,
    backgroundColor: 'white',
    justifyContent: 'center',
    padding: 10,
    paddingTop: 5,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    marginHorizontal: 10,
    marginTop: 2,
    marginBottom: 8,
  },
  textProductOwner: {
    color: 'black',
    fontSize: 16,
    fontWeight: '500',
  },
  line: {
    height: 1,
    marginVertical: 5,
    backgroundColor: Colors.PrimaryColor,
  },
  viewBottomCartItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkBox: {
    height: 20,
    width: 20,
    borderWidth: 2.2,
    borderColor: Colors.PrimaryColor,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconCheckBox: {
    width: 13,
    height: 13,
  },
  viewImage: {
    width: '22%',
    aspectRatio: 1,
    margin: 5,
    marginRight: 10,
    marginBottom: 0,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#adb5bd',
  },
  image: {
    width: '99%',
    aspectRatio: 1,
    borderRadius: 10,
  },
  viewCartItemInfo: {
    alignSelf: 'center',
    justifyContent: 'space-between',
    width: '65%',
  },
  textProductName: {
    flexWrap: 'wrap',
    color: 'black',
    fontWeight: '500',
    fontSize: 15,
  },
  viewBottomInfo: {
    flexDirection: 'row',
    marginTop: 10,
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  viewQuantityHandle: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 4,
    borderWidth: 1.3,
    borderColor: Colors.PrimaryColor,
    height: 22,
  },
  viewIcon: {
    height: 20,
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconMinus: {
    width: 14,
    height: 14,
  },
  iconPlus: {
    width: 16,
    height: 16,
  },
  priceText: {
    color: '#fb5607',
    fontSize: 15,
    fontWeight: '500',
  },
  priceText: {
    color: '#fb5607',
    fontSize: 15,
    fontWeight: '500',
  },
  textUnavailableProduct: {
    position: 'absolute',
    backgroundColor: 'grey',
    color: 'white',
    padding: 10,
    borderBottomLeftRadius: 15,
    right: 10,
    marginTop: 2,
    borderTopRightRadius: 15,
  },
  textInputQuantity: {
    color: 'black',
    fontWeight: '500',
    fontSize: 15,
    padding: 0,
    paddingHorizontal: 1,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: Colors.PrimaryColor,
  },
});
