export const LOGOUT = 'LOGOUT';

export const UPDATEPRODUCT = 'UPDATEPRODUCT';
export const UPDATESUCCESS = 'UPDATESUCCESS';
export const UPDATEFAIL = 'UPDATEFAIL';
export const RESETUPDATE = 'RESETUPDATE';

export const CHANGE_LANGUAGES = 'CHANGELANGUAGES';
export const GET_PRODUCT_BY_USER_ID = 'GETPRODUCTBYUSERID';
export const GET_PRODUCT_BY_USER_ID_SUCCESS = 'GET_PRODUCT_BY_USER_ID_SUCCESS';
export const GET_PRODUCT_BY_USER_ID_FAIL = 'GET_PRODUCT_BY_USER_ID_FAIL';

export const DELELE_PRODUCT = 'DELETEPRODUCT';
export const DELETE_SUCCESS = 'DELETESUCCESS';
export const DELETE_FAIL = 'DELETEFAIL';

export const ADD_NEW_PRODUCT = 'ADDNEWPRODUCT';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADDNEWPRODUCTSUCCESS';
export const ADD_NEW_PRODUCT_FAIL = 'ADDNEWPRODUCTFAIL';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_FAIL = 'ADD_CART_ITEM_FAIL';

export const DELELE_CART_ITEM = 'DELELE_CART_ITEM';
export const DELELE_CART_ITEM_SUCCESS = 'DELELE_CART_ITEM_SUCCESS';
export const DELELE_CART_ITEM_FAIL = 'DELELE_CART_ITEM_FAIL';

export const PURCHASE_CART_ITEM = 'PURCHASE_CART_ITEM';
export const PURCHASE_CART_ITEM_SUCCESS = 'PURCHASE_CART_ITEM_SUCCESS';

export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_FAIL = 'UPDATE_CART_ITEM_FAIL';

export const GET_CART_ITEM_BY_USER_ID = 'GET_CART_ITEM_BY_USER_ID';
export const GET_CART_ITEM_BY_USER_ID_SUCCESS =
  'GET_CART_ITEM_BY_USER_ID_SUCCESS';
export const GET_CART_ITEM_BY_USER_ID_FAIL = 'GET_CART_ITEM_BY_USER_ID_FAIL';

export const BUY_AGAIN = 'BUY_AGAIN';
export const BUY_AGAIN_SUCCESS = 'BUY_AGAIN_SUCCESS';
export const BUY_AGAIN_FAIL = 'BUY_AGAIN_FAIL';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const ADD_NEW_ORDER_SUCCESS = 'ADD_NEW_ORDER_SUCCESS';
export const ADD_NEW_ORDER_FAIL = 'ADD_NEW_ORDER_FAIL';

export const GET_ORDERS_HISTORY_BY_USER_ID = 'GET_ORDERS_HISTORY_BY_USER_ID';
export const GET_ORDERS_HISTORY_BY_USER_ID_SUCCESS =
  'GET_ORDERS_HISTORY_BY_USER_ID_SUCCESS';
export const GET_ORDERS_HISTORY_BY_USER_ID_FAIL =
  'GET_ORDERS_HISTORY_BY_USER_ID_FAIL';
export const RESET_ORDERS_HISTORY = 'RESET_ORDERS_HISTORY';

export const GET_SEARCH_SUGGEST = 'GET_SEARCH_SUGGEST';
export const GET_SEARCH_SUGGEST_SUCCESS = 'GET_SEARCH_SUGGEST_SUCCESS';
export const GET_SEARCH_SUGGEST_FAIL = 'GET_SEARCH_SUGGEST_FAIL';
export const RESET_SEARCH_SUGGEST_HISTORY = 'RESET_SEARCH_SUGGEST_HISTORY';

export const ADD_SEARCH_CONTENT = 'ADD_SEARCH_CONTENT';
export const ADD_SEARCH_CONTENT_SUCCESS = 'ADD_SEARCH_CONTENT_SUCCESS';
export const ADD_SEARCH_CONTENT_FAIL = 'ADD_SEARCH_CONTENT_FAIL';

export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAIL = 'GET_SEARCH_RESULT_FAIL';
export const RESET_SEARCH_RESULT = 'RESET_SEARCH_RESULT';

export const ADD_NEW_FEEDBACK = 'ADD_NEW_FEEDBACK';
export const ADD_NEW_FEEDBACK_SUCCESS = 'ADD_NEW_FEEDBACK_SUCCESS';
export const ADD_NEW_FEEDBACK_FAIL = 'ADD_NEW_FEEDBACK_FAIL';

export const GET_FEEDBACKS_BY_PRODUCT_ID = 'GET_FEEDBACKS_BY_PRODUCT_ID';
export const GET_FEEDBACKS_BY_PRODUCT_ID_SUCCESS =
  'GET_FEEDBACKS_BY_PRODUCT_ID_SUCCESS';
export const GET_FEEDBACKS_BY_PRODUCT_ID_FAIL =
  'GET_FEEDBACKS_BY_PRODUCT_ID_FAIL';
export const RESET_FEEDBACKS = 'RESET_FEEDBACKS';

export const SET_RATING_STATUS = 'SET_RATING_STATUS';
export const RESET_RATING_DONE = 'RESET_RATING_DONE';

// ======================================================================
export const LOGIN = 'LOGIN';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAIL = 'LOGINFAIL';
export const RELOGIN = 'RELOGIN';
export const SIGNUP = 'SIGNUP';
export const GET_HOMEPRODUCT = 'GET_HOMEPRODUCT';
export const GET_BESTSELLERS_SUCCESS = 'GETBESTSELLERSSUCCESS';
export const GET_MOSTVIEWED_SUCCESS = 'GETMOSTVIEWEDSUCCESS';
export const GET_RECENTLYADDED_SUCCESS = 'GETRECENTLYADDEDSUCCESS';
export const GET_MOSTEXPENSIVE_SUCCESS = 'GETMOSTEXPENSIVESUCCESS';
export const GET_ALL_BESTSELLERS_SUCCESS = 'GETALLBESTSELLERSSUCCESS';
export const GET_ALL_MOSTVIEWED_SUCCESS = 'GETALLMOSTVIEWEDSUCCESS';
export const GET_ALL_RECENTLYADDED_SUCCESS = 'GETALLRECENTLYADDEDSUCCESS';
export const GET_ALL_MOSTEXPENSIVE_SUCCESS = 'GETALLMOSTEXPENSIVESUCCESS';
